overrides:
    vite: 'catalog:'

peerDependencyRules:
    allowAny:
        - 'vue'
        - vite
    allowedVersions:
        vite: '*'
catalog:
    vite: npm:@voidzero-dev/vite-plus-core@latest
    vite-plus: latest
allowBuilds:
    '@parcel/watcher': true
